module.exports = {
  BOT_TOKEN: process.env.BOT_TOKEN,
  CLIENT_ID: process.env.CLIENT_ID,
  DATABASE_URL: process.env.DATABASE_URL,
  GIST_ID: process.env.GIST_ID,
  GIST_FILENAME: process.env.GIST_FILENAME,
  GITHUB_PERSONAL_TOKEN: process.env.GITHUB_PERSONAL_TOKEN,
  BOT_NAME: process.env.BOT_NAME,
  BOT_HELP_COMMAND: process.env.BOT_HELP_COMMAND,
  NODE_ENV: process.env.NODE_ENV,
  GOOGLE_SPREADSHEET_URL: process.env.GOOGLE_SPREADSHEET_URL,
  GOOGLE_SERVICE_ACCOUNT_EMAIL: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
  GOOGLE_PRIVATE_KEY: process.env.GOOGLE_PRIVATE_KEY.replace(/\\n/g, "\n"),
};
